// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhnhjG8jq2cPEZvSk6BUCEYYaNVHQhz4',
    appId: '1:760838913725:android:a58e927f61c9d9e82201d4',
    messagingSenderId: '760838913725',
    projectId: 'bookdiscoveryapp-69875',
    storageBucket: 'bookdiscoveryapp-69875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLitwElaK6jCKmFUdbCFOuk77lYJZcHE',
    appId: '1:760838913725:ios:bbbc2e1da9edaf662201d4',
    messagingSenderId: '760838913725',
    projectId: 'bookdiscoveryapp-69875',
    storageBucket: 'bookdiscoveryapp-69875.firebasestorage.app',
    iosClientId: '760838913725-224op400ik5udhtoui5kcq7hbf70gslf.apps.googleusercontent.com',
    iosBundleId: 'com.booksApp.booksDiscoveryApp',
  );
}
